#!/bin/sh

# This file can be redistributed to your source code root,
# to help those who don't have srcdep environment, to fetch dependencies conveniently.

BASEDIR=$(dirname "$0")

mkdir /p "$BASEDIR/.srcdep"
if [ ! -f "$BASEDIR/.srcdep/repo" ]; then
    git clone https://github.com/Streamlet/srcdep.git "$BASEDIR/.srcdep/repo"
fi

source "$BASEDIR/.srcdep/repo/srcdep"
